package joogopay

// Public order statuses. REFUNDED applies only to a returned payout after its
// refund has been credited; payment and checkout statuses are unchanged.
const (
	StatusPending    = "PENDING"
	StatusProcessing = "PROCESSING"
	StatusSucceeded  = "SUCCEEDED"
	StatusFailed     = "FAILED"
	StatusExpired    = "EXPIRED"
	StatusCanceled   = "CANCELED"
	StatusRefunded   = "REFUNDED"
)

// Currency codes accepted by the API; unlisted values pass through unchanged.
const (
	CurrencyBRL = "BRL"

	CurrencyARS = "ARS"
	CurrencyMXN = "MXN"
	CurrencyCOP = "COP"
	CurrencyCLP = "CLP"
	CurrencyPEN = "PEN"
	CurrencyTRY = "TRY"
	CurrencyRUB = "RUB"
	CurrencyUSD = "USD"
	CurrencyBDT = "BDT"
	CurrencyIDR = "IDR"
	CurrencyPHP = "PHP"
	CurrencyPKR = "PKR"
	CurrencyTHB = "THB"
	CurrencyINR = "INR"
)

const (
	CountryBR = "BR"

	CountryAR = "AR"
	CountryMX = "MX"
	CountryCO = "CO"
	CountryCL = "CL"
	CountryPE = "PE"
	CountryTR = "TR"
	CountryRU = "RU"
	CountryUS = "US"
	CountryBD = "BD"
	CountryID = "ID"
	CountryPH = "PH"
	CountryPK = "PK"
	CountryTH = "TH"
	CountryIN = "IN"
)

// PaymentMethod.Code / PayoutMethod.Code values. Pay-in and pay-out share one namespace;
// unlisted values pass through unchanged.
const (
	MethodCodePIX = "PIX"

	MethodCodePagoFacil       = "PAGO_FACIL"
	MethodCodeRapipago        = "RAPIPAGO"
	MethodCodeBankTransfer    = "BANK_TRANSFER"
	MethodCodeCVU             = "CVU"
	MethodCodeQRIS            = "QRIS"
	MethodCodeSPEI            = "SPEI"
	MethodCodeOXXO            = "OXXO"
	MethodCodeCash            = "CASH"
	MethodCodePSE             = "PSE"
	MethodCodeNequi           = "NEQUI"
	MethodCodeTransfiya       = "TRANSFIYA"
	MethodCodeBreb            = "BREB"
	MethodCodeWebpay          = "WEBPAY"
	MethodCodeKhipu           = "KHIPU"
	MethodCodeMach            = "MACH"
	MethodCodePago46          = "PAGO46"
	MethodCodeServiFacil      = "SERVIFACIL"
	MethodCodeEWallet         = "E_WALLET"
	MethodCodeCashApp         = "CASH_APP"
	MethodCodePayPal          = "PAYPAL"
	MethodCodeChime           = "CHIME"
	MethodCodeCreditCard      = "CREDIT_CARD"
	MethodCodeApplePay        = "APPLE_PAY"
	MethodCodeGooglePay       = "GOOGLE_PAY"
	MethodCodeNeteller        = "NETELLER"
	MethodCodeSkrill          = "SKRILL"
	MethodCodeUSDTTRC20       = "USDT-TRC20"
	MethodCodeUSDTERC20       = "USDT-ERC20"
	MethodCodeUSDTBEP20       = "USDT-BEP20"
	MethodCodeBDBkash         = "BD_BKASH"
	MethodCodeBDNagad         = "BD_NAGAD"
	MethodCodeIDVA            = "ID_VA"
	MethodCodeIDQRIS          = "ID_QRIS"
	MethodCodeIDDana          = "ID_DANA"
	MethodCodeIDOvo           = "ID_OVO"
	MethodCodeIDGopay         = "ID_GOPAY"
	MethodCodeIDLinkaja       = "ID_LINKAJA"
	MethodCodeIDShopeepay     = "ID_SHOPEEPAY"
	MethodCodePHGcash         = "PH_GCASH"
	MethodCodePHMaya          = "PH_MAYA"
	MethodCodePHGrab          = "PH_GRAB"
	MethodCodePHQRIS          = "PH_QRIS"
	MethodCodePHGcashQR       = "PH_GCASH_QR"
	MethodCodePHMayaQR        = "PH_MAYA_QR"
	MethodCodePHNativeGcash   = "PH_NATIVE_GCASH"
	MethodCodePKJazzcash      = "PK_JAZZCASH"
	MethodCodePKEasypaisa     = "PK_EASYPAISA"
	MethodCodePKJazzcashQrph  = "PK_JAZZCASH_QRPH"
	MethodCodePKEasypaisaQrph = "PK_EASYPAISA_QRPH"
	MethodCodeTHBankCard      = "TH_BANK_CARD"
	MethodCodeTHTruemoney     = "TH_TRUEMONEY"
	MethodCodeTHPromptpay     = "TH_PROMPTPAY"
	MethodCodeBankCard        = "BANK_CARD"
	MethodCodePapara          = "PAPARA"
	MethodCodeP2P             = "P2P"
	MethodCodeSBP             = "SBP"
	MethodCodeIDBankTransfer  = "ID_BANK_TRANSFER"
	MethodCodePHDfWallet      = "PH_DF_WALLET"
	MethodCodePHDfBank        = "PH_DF_BANK"
	MethodCodePKBank          = "PK_BANK"
	MethodCodeTHBankTransfer  = "TH_BANK_TRANSFER"
	MethodCodeINIFSC          = "IN_IFSC"
	MethodCodeINUPI           = "IN_UPI"
)
